#!/bin/sh

alias cd..="cd .."
alias ..="cd .."
alias ...='cd ../../'
alias ....='cd ../../../'

alias cf="cd ~/.config"

alias untar="tar -zxvf"

alias pac="sudo pacman"

alias grep='grep --color=auto'

alias ls="ls --color=auto"
alias ll="ls -la"

alias mkdir="mkdir -pv"
alias mount='mount |column -t'

alias mv='mv -iv'
alias cp='cp -iv'
alias ln='ln -iv'

alias reboot="reboot"
alias shutdown="shutdown now"

alias please='sudo $(fc -ln -1)'

alias tb="nc termbin.com 9999 | tee /dev/tty | xclip -selection c"
