#!/bin/sh
alias ka="killall" \
	pac="sudo pacman" \
    sctl="sudo systemctl" \
	v="$EDITOR" \
	shutdown="sudo shutdown -h now" \
	ls="ls --color=auto --group-directories-first" \
    la="ls -A --color=auto --group-directories-first" \
    ll="ls -alF" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
	yta="yt -x -f bestaudio/best" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
	wifi="sudo wifi-menu" \
	q="cd .." \
    dot="yadm" \
    ssh="TERM=xterm-256color ssh" \
    vim="nvim" \
    mv="mv -i" \
    mvf="mv" \
    rm="rm -I" \
    rmf="rm" \
    vifm="vifmrun" \
    disk="du -shc * | sort -rh" \
    gs="git status" \


vf() { fzf | xargs -r -I % $EDITOR % ;}
