#!/bin/sh
# global color definitions

export colorbg="#002b36"
export colorfg="#839496"

export color0="#073642"
export color1="#dc322f"
export color2="#859900"
export color3="#b58900"
export color4="#268bd2"
export color5="#d33682"
export color6="#2aa198"
export color7="#eee8d5"

export color8="#4C566A"
export color9="#BF616A"
export color10="#A3BE8C"
export color11="#EBCB8B"
export color12="#81A1C1"
export color13="#B48EAD"
export color14="#8FBCBB"
export color15="#ECEFF4"
