#!/bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width		    2
bspc config window_gap			    5
bspc config top_padding			    0
bspc config split_ratio			    0.5
bspc config borderless_monocle		false
bspc config gapless_monocle		    false
bspc config single_monocle		    true
bspc config focus_follows_pointer	false
bspc config auto_alternate          true
bspc config auto_cancel             true

# colors
bspc config normal_border_color		"#002b36"
bspc config focused_border_color	"#eee8d5"

# rules
bspc rule -a Yad                    state=floating
bspc rule -a Zathura                state=tiled

# start polybar (after bspwm so the module works)
~/.config/polybar/scripts/launch.sh &

# set cursor
xsetroot -cursor_name left_ptr
