#!/bin/sh

function check() {
    echo "$($METHOD | grep -v "\[ignored\]")"
}

function notification() {
    UPDATES="$(check)"
    notify-send "$LOGO $(echo "$UPDATES" | sed '/^$/d' | wc -l) packages need to be updated" "$UPDATES"
}

case $1 in
"--aur")
    METHOD="yay -Qu --aur"
    LOGO=""
;;
"--pac")
    METHOD="pacman -Qu"
    LOGO=""
;;
*) exit 1 ;;
esac

case $2 in
"-p")
    wget -q --spider http://google.com
    
    if [ $? -eq 0 ]; then
        AMOUNT="$(check | sed '/^$/d' | wc -l)"
        if [ "$AMOUNT" == "0" ]; then
            echo ""
        else
            echo "$LOGO $AMOUNT"
        fi
    else
        echo "No connection"
    fi
;;
"-n")
    $(notification)
;;
esac
